Repository BrunoLoFaro/whatsapp-anti-scam-bot, pull requests merged in 2025-06, with the labels that each got.

#12 Add release build workflow with testing capabilities
  .github/workflows/releasing.yml
  .github/workflows/testing.yml
Labels: not-critical

#14 Validación de las keys necesarias
  README.md
  server.ts
Labels: documentation, not-critical

#20 Refactor message handling for improved separation of concerns
  API/handlers/messageReceivedHandler.ts
  Application/usecases/analyzeScamAndRespondUseCase.ts
  Tests/analyzeScamAndRespondUseCase.test.ts
Labels: enhancement, not-critical

#23 Add fallback models to OpenRouter configuration and logging
  Application/usecases/analyzeScamAndRespondUseCase.ts
  Infrastructure/openRouter/openRouter.ts
  README.md
  Tests/openRouter.test.ts
  config.ts
Labels: enhancement, critical

#19 Verificación directorio
  Infrastructure/logging/logger.ts
Labels: bug, documentation, not-critical

#26 Enhance WhatsApp message handling and user interaction flow
  API/handlers/buttonReceivedHandler.ts
  API/handlers/messageReceivedHandler.ts
  API/routes/webhook.route.ts
  Application/usecases/analyzeScamAndRespondUseCase.ts
  Application/usecases/askModelForAdviceUseCase.ts
  Application/usecases/saveMessageUseCase.ts
  Application/usecases/sendSimpleTemplateUseCase.ts
  Application/usecases/sendUserReplyUseCase.ts
  Infrastructure/openRouter/openRouter.ts
  Infrastructure/whatsapp/sendReply.ts
  Infrastructure/whatsapp/sendTemplate.ts
  README.md
  Tests/analyzeScamAndRespondUseCase.test.ts
  Tests/askModelForAdviceUseCase.test.ts
  Tests/openRouter.test.ts
  Tests/sendSimpleTemplateUseCase.test.ts
  Tests/sendTemplate.test.ts
  Tests/sendUserReplyUseCase.test.ts
  Tests/webhook.route.test.ts
  config.ts
Labels: enhancement, critical

#27 v0.2.0-beta
  .github/workflows/releasing.yml
  API/handlers/buttonReceivedHandler.ts
  API/handlers/messageReceivedHandler.ts
  API/routes/info.health.route.ts
  API/routes/webhook.route.ts
  Application/usecases/analyzeScamAndRespondUseCase.ts
  Application/usecases/askModelForAdviceUseCase.ts
  Application/usecases/saveMessageUseCase.ts
  Application/usecases/sendSimpleTemplateUseCase.ts
  Application/usecases/sendUserReplyUseCase.ts
  Infrastructure/logging/logger.ts
  Infrastructure/openRouter/openRouter.ts
  Infrastructure/whatsapp/sendReply.ts
  Infrastructure/whatsapp/sendTemplate.ts
  README.md
  Tests/analyzeScamAndRespondUseCase.test.ts
  Tests/askModelForAdviceUseCase.test.ts
  Tests/info.health.route.test.ts
  Tests/openRouter.test.ts
  Tests/sendSimpleTemplateUseCase.test.ts
  Tests/sendTemplate.test.ts
  Tests/sendUserReplyUseCase.test.ts
  Tests/webhook.route.test.ts
  config.ts
  server.ts
Labels: documentation, enhancement, not-critical
